### ISSUE TITLE
vue2.x+elementUI怎么改造？

### ISSUE THREAD

**Issue by kaiziwen** [qq1037305420/element-plus#5]
大佬，想请教一下vue2.x+elementUI怎么改造？

**Comment by qq1037305420** [comment]
https://github.com/formilyjs/element
这个里面有个半成品（响应式结合有些问题，部分组件没有集成），如果需要修改把vue3这个复制多去80%能用吧，修改下jsx和compostion/api就可以
vue3的是根据这个改的
https://github.com/formilyjs/element/blob/main/packages/renderer/package.json 启动时候跑这个里面的serve就可以了
